In [2]:
import numpy as np

In [13]:
 x = 1/2 *((np.zeros((1,2),dtype=np.float32)) + np.ones((1,2),dtype=np.float32))

In [14]:
print(x)

[[0.5 0.5]]


In [22]:
train_labels = np.genfromtxt('/model/cnnOut',
                                 dtype=np.float32)

In [23]:
print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [24]:
train_labels = np.column_stack((train_labels,np.ones(train_labels.shape[0],dtype=np.float32)))

In [26]:
print(train_labels)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [27]:
np.savetxt('/model/addedwinner',train_labels)

In [32]:
w = open('/model/addedwinner','w')

AttributeError: 'str' object has no attribute 'append'